import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <div className="mx-auto bg-gray-300 ">
          <p className=" text-center">This is the main page</p>
        </div>
        <h1 className="ml-230">Blog Articles</h1>
        <div className="flex flex-row gap-5 mx-auto">{children}</div>
      </body>
    </html>
  );
}
